server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.pojo

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_11_21?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: listen