# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test20201017(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_20201017(self):
        # Test name: 20201017
        # Step # | name | target | value | comment
        # 1 | open | / |  |
        self.driver.get("https://www.baidu.com/")
        # 2 | setWindowSize | 1550x838 |  |
        # self.driver.set_window_size(1550, 838)
        # 3 | click | id=kw |  |
        self.driver.find_element(By.ID, "kw").click()
        # 4 | type | id=kw | 尚文媛是猪 |
        self.driver.find_element(By.ID, "kw").send_keys("尚文媛是猪")
        # 5 | click | id=su |  |
        self.driver.find_element(By.ID, "su").click()
        # 6 | click | id=kw |  |
        self.driver.find_element(By.ID, "kw").click()
        # 7 | click | id=kw |  |
        self.driver.find_element(By.ID, "kw").click()
        # 8 | click | id=kw |
        self.driver.find_element(By.ID, "kw").click()
        # 9 | type | id=kw | 尚文媛喜欢李星亚吗 |
        self.driver.find_element(By.ID, "kw").send_keys("")
        time.sleep(5)
        self.driver.find_element(By.ID, "kw").send_keys("尚文媛喜欢李星亚吗")
        self.driver.find_element(By.ID, "kw").click()
        time.sleep(10)

